using Array2x2;

Matrix m1 = new();
Console.WriteLine("Создана матрица 1");
Console.WriteLine(m1);
Console.WriteLine();
int[,] array2 = { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } };
Matrix m2 = new(array2);
Console.WriteLine("Создана матрица 2");
Console.WriteLine(m2);
Console.WriteLine();
int[,] array3 = { { 1, 2 }, { 3, 4 } };
Matrix m3 = new(array3);
Console.WriteLine("Создана матрица 3");
Console.WriteLine(m3);
Console.WriteLine();
int[,] array4 = { { 1 }, { 4 } };
Matrix m4 = new(array4);
Console.WriteLine("Создана матрица 4");
Console.WriteLine(m4);
Console.WriteLine();
Console.WriteLine("Сложим матрицу 2 и 3");
Console.WriteLine(m2 + m3);
Console.WriteLine("Вычтем из матрицы 2 матрицу 3");
Console.WriteLine(m2 - m3);
Console.WriteLine("Умножим матрицу 2 на матрицу 3");
Console.WriteLine(m2 * m3);
Console.WriteLine("Проинкрементируем матрицу 2");
Console.WriteLine(m2++);
Console.WriteLine("Продекрементируем матрицу 3");
Console.WriteLine(m3--);
Console.WriteLine("Умножим матрицу 2 на 2");
Console.WriteLine(m2 * 2);
Console.WriteLine("Разделим матрицу 2 на 2");
Console.WriteLine(m2 / 2);
Console.WriteLine("Сравним матрицы 2 и 3");
Console.WriteLine($"Матрица 2 == матрица 3? {m2 == m3}");
Console.WriteLine($"Матрица 2 != матрица 3? {m2 != m3}");
Console.Write($"Проверим матрица 2 true или false: ");
if (m2) Console.Write("Определитель != 0, т.е. матрица true\n");
else Console.Write("Определитель = 0б т.е. матрица false\n");
Console.WriteLine($"Преобразуем матрицу 3 в число = {(int)m3}");
Console.WriteLine($"Преобразуем число 2 в матрицу\n {(Matrix)2}");

